# set -g default-terminal "tmux-256color*:Tc"
# set-option -g default-terminal "xterm-256color"
set-option -g default-terminal "screen-256color"
set-option -a terminal-features 'XXX:RGB'
# set-option -ga terminal-overrides ",xterm-256color-italic:Tc"

set -s escape-time 0
set-option -g detach-on-destroy off

set -g status-left-length 40
set -g status-justify centre
setw -g window-status-current-style fg=black,bg=white
set -g bell-action none
set -g set-titles on
set -g set-titles-string "#S"
set -g history-limit 50000
set focus-events

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -g status-style 'bg=#333333 fg=#5eacd3'

bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"
set -g base-index 1
set -g pane-base-index 1

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe 'xclip -in -selection clipboard'
bind -T copy-mode-vi MouseDragEnd1Pane  send-keys -X copy-pipe "pbcopy"

## Untested
# bind-key -T copy-mode-vi Escape send -X cancel
# bind-key -n C-v run-shell "xclip -o -sel clipboard | tmux load-buffer - && tmux paste-buffer"

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind-key f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"
bind-key g run-shell "tmux neww ~/.local/bin/tmux-sessions-fzf"

set -g mouse 1
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
